package tests;

import Exceptions.NotEnoughPoints;
import model.LoanItem;
import model.UrgentReturn;
import model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;


import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

public class ExceptionTests {

//    @Test
//    public void testEnoughPoints(){
//        User testUser = new User("Sarah", "sarah@gmail.com", 10, new ArrayList<>());
//        LoanItem testItem = new UrgentReturn("cardigan", "black", "medium", true, 10, 28, "Sarah");
//
//        try {
//            testUser.loanItem(testItem);
//        } catch (NotEnoughPoints notEnoughPoints) {
//            fail("User has enough points");
//        }
//
//        //assertTrue()
//    }
//
//    @Test
//    public void notEnoughPoints(){
//        User testUser = new User("Sarah", "sarah@gmail.com", 1, new ArrayList<>());
//        LoanItem testItem = new UrgentReturn("cardigan", "black", "medium", true, 10, 28, "Sarah");
//
//        try {
//            testUser.loanItem(testItem);
//        } catch (NotEnoughPoints notEnoughPoints) {
//                //
//            }
//        }
    }

